name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        
    - name: Build with Maven
      run: |
        cd rutherford-d1
        mvn clean package -DskipTests
        
    - name: Generate deployment package
      run: |
        zip -r deploy.zip . -x "*.git*" "*node_modules*"
        
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: rutherford-diagnostics
        environment_name: rutherford-env
        version_label: ${{ github.sha }}
        region: us-east-1
        deployment_package: deploy.zip 